# Generated by Django 5.2.16 on 2026-07-29 08:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opd', '0004_alter_kopsurat_options_alter_opd_options_and_more'),
        ('pegawai', '0010_alter_bidang_options_alter_eselon_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KlasifikasiSurat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=30, unique=True)),
                ('nama', models.CharField(max_length=150)),
                ('keterangan', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Klasifikasi Surat',
                'verbose_name_plural': 'Klasifikasi Surat',
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='Surat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('masuk', 'Surat Masuk'), ('keluar', 'Surat Keluar')], max_length=10)),
                ('nomor_agenda', models.CharField(blank=True, max_length=50)),
                ('nomor_surat', models.CharField(blank=True, max_length=100)),
                ('tanggal_surat', models.DateField()),
                ('tanggal_diterima', models.DateField(blank=True, null=True)),
                ('tanggal_dikirim', models.DateField(blank=True, null=True)),
                ('asal_surat', models.CharField(blank=True, max_length=255)),
                ('tujuan_surat', models.CharField(blank=True, max_length=255)),
                ('perihal', models.CharField(max_length=255)),
                ('ringkasan', models.TextField(blank=True)),
                ('sifat', models.CharField(choices=[('biasa', 'Biasa'), ('penting', 'Penting'), ('segera', 'Segera'), ('sangat_segera', 'Sangat Segera'), ('rahasia', 'Rahasia')], default='biasa', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('diajukan', 'Diajukan Staf'), ('diverifikasi_kasi', 'Diverifikasi Kasi'), ('dikembalikan', 'Dikembalikan'), ('divalidasi', 'Divalidasi'), ('didisposisi', 'Didisposisi'), ('didistribusikan', 'Didistribusikan'), ('selesai', 'Selesai'), ('diarsipkan', 'Diarsipkan')], default='draft', max_length=30)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('bidang_pembuat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surat_dibuat', to='pegawai.bidang')),
                ('dibuat_oleh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surat_dibuat', to=settings.AUTH_USER_MODEL)),
                ('diperbarui_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surat_diperbarui', to=settings.AUTH_USER_MODEL)),
                ('klasifikasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surat', to='surat.klasifikasisurat')),
                ('penanggung_jawab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surat_tanggung_jawab', to='pegawai.pegawai')),
                ('unit_pengolah', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surat_unit_pengolah', to='opd.subopd')),
            ],
            options={
                'verbose_name': 'Surat',
                'verbose_name_plural': 'Surat',
                'ordering': ['-tanggal_surat', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RiwayatSurat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aksi', models.CharField(max_length=100)),
                ('status_sebelum', models.CharField(blank=True, max_length=30)),
                ('status_sesudah', models.CharField(blank=True, max_length=30)),
                ('keterangan', models.TextField(blank=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riwayat_surat', to=settings.AUTH_USER_MODEL)),
                ('surat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat', to='surat.surat')),
            ],
            options={
                'verbose_name': 'Riwayat Surat',
                'verbose_name_plural': 'Riwayat Surat',
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='ReviewSurat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahap', models.CharField(choices=[('verifikasi_kasi', 'Verifikasi Kasi'), ('validasi_sekretaris', 'Validasi Sekretaris'), ('validasi_kepala', 'Validasi Kepala')], max_length=30)),
                ('keputusan', models.CharField(choices=[('setuju', 'Setuju'), ('revisi', 'Revisi'), ('tolak', 'Tolak')], max_length=10)),
                ('catatan', models.TextField(blank=True)),
                ('dibuat_pada', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_surat', to='pegawai.pegawai')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_surat', to=settings.AUTH_USER_MODEL)),
                ('surat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='surat.surat')),
            ],
            options={
                'verbose_name': 'Review Surat',
                'verbose_name_plural': 'Review Surat',
                'ordering': ['surat', 'dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='LampiranSurat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('berkas', models.FileField(upload_to='surat/lampiran/%Y/%m/')),
                ('keterangan', models.CharField(blank=True, max_length=255)),
                ('diunggah_pada', models.DateTimeField(auto_now_add=True)),
                ('diunggah_oleh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lampiran_surat', to=settings.AUTH_USER_MODEL)),
                ('surat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lampiran', to='surat.surat')),
            ],
            options={
                'verbose_name': 'Lampiran Surat',
                'verbose_name_plural': 'Lampiran Surat',
                'ordering': ['surat', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='DisposisiSurat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_disposisi', models.CharField(blank=True, max_length=50)),
                ('instruksi', models.TextField()),
                ('catatan', models.TextField(blank=True)),
                ('batas_waktu', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('dikirim', 'Dikirim'), ('ditindaklanjuti', 'Ditindaklanjuti'), ('selesai', 'Selesai')], default='draft', max_length=20)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('dikirim_pada', models.DateTimeField(blank=True, null=True)),
                ('dibuat_oleh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposisi_dibuat', to=settings.AUTH_USER_MODEL)),
                ('pemberi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposisi_diberikan', to='pegawai.pegawai')),
                ('surat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposisi', to='surat.surat')),
            ],
            options={
                'verbose_name': 'Disposisi Surat',
                'verbose_name_plural': 'Disposisi Surat',
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='TujuanDisposisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('belum_dibaca', 'Belum Dibaca'), ('dibaca', 'Dibaca'), ('diproses', 'Diproses'), ('selesai', 'Selesai')], default='belum_dibaca', max_length=20)),
                ('catatan_tindak_lanjut', models.TextField(blank=True)),
                ('dibaca_pada', models.DateTimeField(blank=True, null=True)),
                ('selesai_pada', models.DateTimeField(blank=True, null=True)),
                ('bidang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tujuan_disposisi', to='pegawai.bidang')),
                ('disposisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tujuan', to='surat.disposisisurat')),
                ('penerima', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tujuan_disposisi', to='pegawai.pegawai')),
            ],
            options={
                'verbose_name': 'Tujuan Disposisi',
                'verbose_name_plural': 'Tujuan Disposisi',
                'ordering': ['disposisi', 'bidang__bidang'],
            },
        ),
        migrations.AddIndex(
            model_name='surat',
            index=models.Index(fields=['jenis', 'status'], name='surat_surat_jenis_d4fd7c_idx'),
        ),
        migrations.AddIndex(
            model_name='surat',
            index=models.Index(fields=['nomor_agenda'], name='surat_surat_nomor_a_918902_idx'),
        ),
        migrations.AddIndex(
            model_name='surat',
            index=models.Index(fields=['nomor_surat'], name='surat_surat_nomor_s_9a03e2_idx'),
        ),
        migrations.AddIndex(
            model_name='surat',
            index=models.Index(fields=['tanggal_surat'], name='surat_surat_tanggal_35af67_idx'),
        ),
        migrations.AddConstraint(
            model_name='surat',
            constraint=models.UniqueConstraint(condition=models.Q(('nomor_agenda', ''), _negated=True), fields=('jenis', 'nomor_agenda', 'unit_pengolah'), name='uniq_nomor_agenda_per_jenis_unit'),
        ),
        migrations.AddConstraint(
            model_name='surat',
            constraint=models.UniqueConstraint(condition=models.Q(('nomor_surat', ''), _negated=True), fields=('jenis', 'nomor_surat', 'unit_pengolah'), name='uniq_nomor_surat_per_jenis_unit'),
        ),
        migrations.AddIndex(
            model_name='riwayatsurat',
            index=models.Index(fields=['aksi'], name='surat_riway_aksi_0c7a60_idx'),
        ),
        migrations.AddIndex(
            model_name='riwayatsurat',
            index=models.Index(fields=['dibuat_pada'], name='surat_riway_dibuat__352368_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewsurat',
            index=models.Index(fields=['tahap', 'keputusan'], name='surat_revie_tahap_e4bb34_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewsurat',
            index=models.Index(fields=['dibuat_pada'], name='surat_revie_dibuat__b62e5b_idx'),
        ),
        migrations.AddIndex(
            model_name='disposisisurat',
            index=models.Index(fields=['status'], name='surat_dispo_status_d9d8f1_idx'),
        ),
        migrations.AddIndex(
            model_name='disposisisurat',
            index=models.Index(fields=['batas_waktu'], name='surat_dispo_batas_w_60ea96_idx'),
        ),
        migrations.AddConstraint(
            model_name='tujuandisposisi',
            constraint=models.UniqueConstraint(fields=('disposisi', 'bidang'), name='uniq_bidang_per_disposisi'),
        ),
    ]
