# Generated by Django 5.2.16 on 2026-08-04 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opd', '0004_alter_kopsurat_options_alter_opd_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisDokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Jenis Dokumen',
                'verbose_name_plural': 'Jenis Dokumen',
            },
        ),
        migrations.CreateModel(
            name='DraftSurat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=30, unique=True)),
                ('sifat', models.CharField(max_length=255)),
                ('lampiran', models.CharField(max_length=255)),
                ('hal', models.CharField(max_length=255)),
                ('dari', models.CharField(max_length=255)),
                ('alamat', models.CharField(max_length=255)),
                ('pembuka', models.TextField()),
                ('isi', models.TextField()),
                ('penutup', models.TextField()),
                ('tembusan', models.TextField()),
                ('pejabat_penandatangan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_surat', to='opd.penandatangan')),
                ('jenis_dokumen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_surat', to='draft.jenisdokumen')),
            ],
            options={
                'verbose_name': 'Draft Surat',
                'verbose_name_plural': 'Draft Surat',
            },
        ),
        migrations.CreateModel(
            name='TujuanSurat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instansi', models.CharField(max_length=255)),
                ('draft_surat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tujuansurat', to='draft.draftsurat')),
            ],
            options={
                'verbose_name': 'Tujuan Surat',
                'verbose_name_plural': 'Tujuan Surat',
            },
        ),
        migrations.CreateModel(
            name='Undangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggalmulai', models.DateField()),
                ('tanggalselesai', models.DateField()),
                ('jammulai', models.TimeField()),
                ('jamselesai', models.CharField(max_length=255)),
                ('tempat', models.CharField(max_length=255)),
                ('agenda', models.TextField()),
                ('perlengkapan', models.TextField()),
                ('draft_surat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='undangan', to='draft.draftsurat')),
            ],
            options={
                'verbose_name': 'Undangan',
                'verbose_name_plural': 'Undangan',
            },
        ),
    ]
