# Generated by Django 5.2.16 on 2026-07-24 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opd', '0002_alter_opd_kode_alter_subopd_kode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=30, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('sub_opd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pegawais', to='opd.subopd')),
            ],
            options={
                'verbose_name': 'Pegawai',
                'verbose_name_plural': 'Pegawai',
                'ordering': ['nip'],
            },
        ),
    ]
