# Generated by Django 5.2.16 on 2026-07-27 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidang', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Bidang',
                'verbose_name_plural': 'Bidang',
                'ordering': ['bidang'],
            },
        ),
        migrations.CreateModel(
            name='Eselon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eselon', models.CharField(max_length=255)),
                ('urutan', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Eselon',
                'verbose_name_plural': 'Eselon',
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='Pangkat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pangkat', models.CharField(max_length=255)),
                ('golongan', models.CharField(max_length=10)),
                ('ruang', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Pangkat',
                'verbose_name_plural': 'Pangkat',
                'ordering': ['pangkat'],
            },
        ),
        migrations.AddField(
            model_name='pegawai',
            name='bidang',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pegawais', to='pegawai.bidang'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pegawai',
            name='eselon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pegawais', to='pegawai.eselon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pegawai',
            name='pangkat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pegawais', to='pegawai.pangkat'),
            preserve_default=False,
        ),
    ]
