# Generated by Django 5.2.16 on 2026-07-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0002_bidang_eselon_pangkat_pegawai_bidang_pegawai_eselon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisJabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150, unique=True)),
                ('keterangan', models.CharField(blank=True, max_length=200, null=True)),
                ('fungsi', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Jenis Jabatan',
                'verbose_name_plural': 'Jenis Jabatan',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StatusASN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Status ASN',
                'verbose_name_plural': 'Status ASN',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, unique=True)),
                ('keterangan', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Tugas',
                'verbose_name_plural': 'Tugas',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='bidang',
            options={'ordering': ['id'], 'verbose_name': 'Bidang', 'verbose_name_plural': 'Bidang'},
        ),
        migrations.AlterModelOptions(
            name='pangkat',
            options={'ordering': ['golongan', 'ruang'], 'verbose_name': 'Pangkat', 'verbose_name_plural': 'Pangkat'},
        ),
        migrations.AddConstraint(
            model_name='pangkat',
            constraint=models.UniqueConstraint(fields=('pangkat', 'golongan', 'ruang'), name='unique_pangkat_golongan_ruang'),
        ),
    ]
