# Generated by Django 5.2.16 on 2026-07-28 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0003_jenisjabatan_statusasn_tugas_alter_bidang_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawai',
            name='jabatan',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pegawai',
            name='jenis_jabatan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pegawais', to='pegawai.jenisjabatan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pegawai',
            name='status_asn',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pegawais', to='pegawai.statusasn'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pegawai',
            name='tugas',
            field=models.ManyToManyField(blank=True, related_name='pegawais', to='pegawai.tugas'),
        ),
    ]
