# Generated by Django 5.2.16 on 2026-07-28 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0004_pegawai_jabatan_pegawai_jenis_jabatan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pegawai',
            name='tugas',
        ),
        migrations.AddField(
            model_name='pegawai',
            name='tugas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pegawais', to='pegawai.tugas'),
            preserve_default=False,
        ),
    ]
