# Generated by Django 5.2.16 on 2026-07-28 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0005_remove_pegawai_tugas_pegawai_tugas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tingkat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tingkat', models.CharField(max_length=100, unique=True)),
                ('ket', models.CharField(blank=True, max_length=200, null=True)),
                ('pesawat', models.CharField(blank=True, max_length=100, null=True)),
                ('kapal', models.CharField(blank=True, max_length=100, null=True)),
                ('keretaapian', models.CharField(blank=True, max_length=200, null=True)),
                ('lainnya', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Tingkat',
                'verbose_name_plural': 'Tingkat',
                'ordering': ['tingkat'],
            },
        ),
        migrations.AddField(
            model_name='pegawai',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pegawai/foto/'),
        ),
        migrations.AddField(
            model_name='pegawai',
            name='tgl_lahir',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pegawai',
            name='tingkat_spd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pegawais', to='pegawai.tingkat'),
        ),
    ]
