# Generated by Django 5.2.16 on 2026-07-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0006_tingkat_pegawai_foto_pegawai_tgl_lahir_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pegawai',
            options={'ordering': ['eselon__urutan', '-tgl_lahir'], 'verbose_name': 'Pegawai', 'verbose_name_plural': 'Pegawai'},
        ),
    ]
