# Generated by Django 5.2.16 on 2026-07-28 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0008_alter_pegawai_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pegawai',
            options={'verbose_name': 'Pegawai', 'verbose_name_plural': 'Pegawai'},
        ),
    ]
