# Generated by Django 5.2.16 on 2026-07-28 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0009_alter_pegawai_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bidang',
            options={'verbose_name': 'Bidang', 'verbose_name_plural': 'Bidang'},
        ),
        migrations.AlterModelOptions(
            name='eselon',
            options={'verbose_name': 'Eselon', 'verbose_name_plural': 'Eselon'},
        ),
        migrations.AlterModelOptions(
            name='jenisjabatan',
            options={'verbose_name': 'Jenis Jabatan', 'verbose_name_plural': 'Jenis Jabatan'},
        ),
        migrations.AlterModelOptions(
            name='pangkat',
            options={'verbose_name': 'Pangkat', 'verbose_name_plural': 'Pangkat'},
        ),
        migrations.AlterModelOptions(
            name='statusasn',
            options={'verbose_name': 'Status ASN', 'verbose_name_plural': 'Status ASN'},
        ),
        migrations.AlterModelOptions(
            name='tingkat',
            options={'verbose_name': 'Tingkat', 'verbose_name_plural': 'Tingkat'},
        ),
        migrations.AlterModelOptions(
            name='tugas',
            options={'verbose_name': 'Tugas', 'verbose_name_plural': 'Tugas'},
        ),
    ]
