# Generated by Django 5.2.16 on 2026-07-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informasi',
            name='nama',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='unit',
            name='nama',
            field=models.TextField(),
        ),
    ]
