# Generated by Django 5.2.16 on 2026-07-20 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'OPD',
                'verbose_name_plural': 'OPD',
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='SubOPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('opd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_opds', to='opd.opd')),
            ],
            options={
                'verbose_name': 'Sub OPD',
                'verbose_name_plural': 'Sub OPD',
                'ordering': ['kode'],
            },
        ),
    ]
