# Generated by Django 5.2.16 on 2026-07-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opd',
            name='kode',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='subopd',
            name='kode',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
