# Generated by Django 5.2.16 on 2026-07-28 04:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0002_alter_opd_kode_alter_subopd_kode'),
        ('pegawai', '0003_jenisjabatan_statusasn_tugas_alter_bidang_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subopd',
            name='opd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subopd', to='opd.opd'),
        ),
        migrations.CreateModel(
            name='Pemda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pemda', models.CharField(max_length=200)),
                ('nama_kabupaten', models.CharField(blank=True, max_length=200, null=True)),
                ('ibukota', models.CharField(blank=True, max_length=100, null=True)),
                ('alamat', models.CharField(blank=True, max_length=300, null=True)),
                ('telepon', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('password_standar', models.CharField(blank=True, default='', help_text='Password standar untuk login pegawai dengan NIP.', max_length=128)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='pemda_logos/')),
                ('nama_dinas', models.OneToOneField(error_messages={'unique': 'Nama Dinas sudah digunakan. Pilih nama dinas lain.'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pemda', to='opd.subopd')),
            ],
            options={
                'verbose_name': 'Pemda',
                'verbose_name_plural': 'Pemda',
                'ordering': ['nama_pemda'],
            },
        ),
        migrations.CreateModel(
            name='KopSurat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_family', models.CharField(choices=[('Arial, sans-serif', 'Arial'), ('"Times New Roman", Times, serif', 'Times New Roman'), ('Calibri, Arial, sans-serif', 'Calibri'), ('Cambria, Georgia, serif', 'Cambria'), ('Garamond, "Times New Roman", serif', 'Garamond'), ('Tahoma, Geneva, sans-serif', 'Tahoma'), ('Verdana, Geneva, sans-serif', 'Verdana')], default='Arial', max_length=120, verbose_name='Jenis Font')),
                ('region_font_size_pt', models.PositiveSmallIntegerField(default=14, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(32)], verbose_name='Ukuran Font Nama Pemda (pt)')),
                ('office_font_size_pt', models.PositiveSmallIntegerField(default=18, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(36)], verbose_name='Ukuran Font Nama Dinas/Jabatan (pt)')),
                ('address_font_size_pt', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(20)], verbose_name='Ukuran Font Alamat (pt)')),
                ('contact_font_size_pt', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(20)], verbose_name='Ukuran Font Kontak (pt)')),
                ('logo_width_px', models.PositiveSmallIntegerField(default=90, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(180)], verbose_name='Lebar Logo (px)')),
                ('logo_height_px', models.PositiveSmallIntegerField(default=90, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(180)], verbose_name='Tinggi Logo (px)')),
                ('print_scale_percent', models.PositiveSmallIntegerField(default=96, validators=[django.core.validators.MinValueValidator(75), django.core.validators.MaxValueValidator(120)], verbose_name='Skala Cetak Default (%)')),
                ('margin_top_mm', models.PositiveSmallIntegerField(default=18, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Margin Atas (mm)')),
                ('margin_bottom_mm', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Margin Bawah (mm)')),
                ('margin_left_mm', models.PositiveSmallIntegerField(default=18, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Margin Kiri (mm)')),
                ('margin_right_mm', models.PositiveSmallIntegerField(default=18, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Margin Kanan (mm)')),
                ('default_number_format', models.CharField(blank=True, default='800.1.11.1/{nomor_urut}/BKAD/{bulan}/{tahun}', help_text='Gunakan {nomor_urut}, {bulan}, {tahun} sebagai placeholder', max_length=100, verbose_name='Format Default Nomor SPT')),
                ('pemda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kop_surat', to='opd.pemda')),
            ],
            options={
                'verbose_name': 'Kop Surat',
                'verbose_name_plural': 'Kop Surat',
                'ordering': ['pemda__nama_pemda'],
            },
        ),
        migrations.CreateModel(
            name='Penandatangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('nip', models.CharField(blank=True, max_length=30, null=True)),
                ('jabatan', models.CharField(blank=True, max_length=200, null=True)),
                ('jenis_jabatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penandatangan', to='pegawai.jenisjabatan')),
                ('pangkat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penandatangan', to='pegawai.pangkat')),
                ('subopd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penandatangan', to='opd.subopd')),
                ('tugas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penandatangan', to='pegawai.tugas')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('nama', 'tugas', 'jenis_jabatan', 'subopd'), name='uniq_penandatangan_nama_tugas_jenis_jabatan_subopd', violation_error_message='Penandatangan dengan Nama, tugas, jenis jabatan, dan OPD yang sama sudah ada.')],
            },
        ),
    ]
