# Generated by Django 5.2.16 on 2026-07-28 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0003_alter_subopd_opd_pemda_kopsurat_penandatangan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kopsurat',
            options={'verbose_name': 'Kop Surat', 'verbose_name_plural': 'Kop Surat'},
        ),
        migrations.AlterModelOptions(
            name='opd',
            options={'verbose_name': 'OPD', 'verbose_name_plural': 'OPD'},
        ),
        migrations.AlterModelOptions(
            name='pemda',
            options={'verbose_name': 'Pemda', 'verbose_name_plural': 'Pemda'},
        ),
        migrations.AlterModelOptions(
            name='subopd',
            options={'verbose_name': 'Sub OPD', 'verbose_name_plural': 'Sub OPD'},
        ),
    ]
